#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Installs the Helpdesktool Windows endpoint agent as a boot-persistent,
  auto-restarting Windows Service running under a dedicated, low-privilege
  service account -- not an interactive admin account, not LocalSystem.

.DESCRIPTION
  Minimal customer interaction by design: given a control-plane URL and a
  one-time enrollment token (generated by an admin via
  POST /v1/devices/enrollment-tokens, or the operator console's Devices
  page), this is the only command needed to install, enroll, and start the
  agent. Safe to re-run -- an already-enrolled device is left untouched.

  Packaging note: this repository has no published PyPI/private-index
  release yet, so -PackageSource defaults to installing straight from this
  repo's default branch via pip's git+https support -- fine for a demo/
  pilot, but for a real fleet rollout, publish a pinned wheel/sdist to a
  private index (or a signed release archive) and pass that via
  -PackageSource instead, so every endpoint installs an exact, reviewed
  version rather than "whatever main currently is."

.PARAMETER ServerUrl
  Control plane URL, e.g. https://api.example.com

.PARAMETER EnrollmentToken
  One-time admin-issued enrollment token.

.PARAMETER AllowedServices
  Comma-separated Windows service names (as shown by Get-Service) this
  device is allowed to restart.

.PARAMETER ExternalId
  Defaults to this host's hostname.

.PARAMETER PackageSource
  A pip-installable target (PyPI name, git+https URL, or local wheel path).

.EXAMPLE
  .\install-windows-agent.ps1 -ServerUrl https://api.example.com -EnrollmentToken abc123 -AllowedServices Spooler
#>
param(
    [Parameter(Mandatory = $true)][string]$ServerUrl,
    [Parameter(Mandatory = $true)][string]$EnrollmentToken,
    [string]$AllowedServices = "",
    [string]$ExternalId = $env:COMPUTERNAME,
    [string]$PackageSource = "git+https://github.com/abdulnajam-boop/helpdesktool.git@main#egg=helpdesktool[windows]",
    [string]$ServiceAccount = "NT SERVICE\HelpdeskWindowsAgent"
)

$ErrorActionPreference = "Stop"

$InstallDir = "C:\Program Files\Helpdesktool"
$ConfigDir = "C:\ProgramData\helpdesktool"
$ConfigFile = Join-Path $ConfigDir "agent.json"
$ServiceName = "HelpdeskWindowsAgent"

function Assert-Python311 {
    $pythonCmd = Get-Command python -ErrorAction SilentlyContinue
    if (-not $pythonCmd) {
        throw "python was not found on PATH -- install Python 3.11 or newer from python.org first"
    }
    $versionOutput = & python --version 2>&1
    $version = [version]($versionOutput -replace "Python ", "")
    if ($version -lt [version]"3.11.0") {
        throw "python is $versionOutput, but helpdesktool requires 3.11+. Install a newer Python from python.org and re-run."
    }
}

Write-Host "==> Checking prerequisites"
Assert-Python311

Write-Host "==> Installing helpdesktool into $InstallDir (isolated virtualenv)"
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
python -m venv "$InstallDir\venv"
& "$InstallDir\venv\Scripts\pip.exe" install --upgrade pip --quiet
& "$InstallDir\venv\Scripts\pip.exe" install --upgrade $PackageSource --quiet

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

if (Test-Path $ConfigFile) {
    Write-Host "==> $ConfigFile already exists; leaving enrollment untouched (re-running is safe)"
} else {
    Write-Host "==> Enrolling device with the control plane"
    $enrollArgs = @(
        "--config", $ConfigFile,
        "--server-url", $ServerUrl,
        "--enrollment-token", $EnrollmentToken,
        "--external-id", $ExternalId,
        "--once"
    )
    if ($AllowedServices) {
        $enrollArgs += @("--allowed-services", $AllowedServices)
    }
    & "$InstallDir\venv\Scripts\helpdesk-windows-agent.exe" @enrollArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Enrollment failed (exit code $LASTEXITCODE) -- check the token hasn't expired or already been used."
    }
}

Write-Host "==> Restricting $ConfigDir to the service account and Administrators"
icacls $ConfigDir /inheritance:r | Out-Null
icacls $ConfigDir /grant "${ServiceAccount}:(OI)(CI)F" | Out-Null
icacls $ConfigDir /grant "BUILTIN\Administrators:(OI)(CI)F" | Out-Null

Write-Host "==> Installing Windows Service"
$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "==> Service already installed; leaving it as-is (re-running is safe)"
} else {
    # --username/--password run the service under the low-privilege virtual
    # account ($ServiceAccount, "NT SERVICE\HelpdeskWindowsAgent" by
    # default) instead of pywin32's own default of LocalSystem -- a virtual
    # service account needs no password (Windows manages it), which is why
    # this matches the ACLs granted below. Skipping these flags would leave
    # the service running as LocalSystem, silently defeating the whole
    # point of restricting C:\ProgramData\helpdesktool's ACL.
    & "$InstallDir\venv\Scripts\helpdesk-windows-agent-service.exe" `
        --startup auto --username $ServiceAccount --password "" install
    if ($LASTEXITCODE -ne 0) {
        throw "Service install failed (exit code $LASTEXITCODE)"
    }
    # Auto-restart on failure -- the SCM-native equivalent of the Linux
    # unit's Restart=on-failure / RestartSec=10.
    sc.exe failure $ServiceName reset= 86400 actions= restart/10000/restart/10000/restart/10000 | Out-Null
}

Start-Service -Name $ServiceName
Write-Host "==> Done. Check status with: Get-Service $ServiceName"
Write-Host "==> Event log: Get-EventLog -LogName Application -Source $ServiceName -Newest 20"
