#!/usr/bin/env bash
# Installs the Helpdesktool Linux endpoint agent as a boot-persistent,
# auto-restarting systemd service running under a dedicated, unprivileged
# service account -- not root, not an interactive user's own login session.
#
# Minimal customer interaction by design: given a control-plane URL and a
# one-time enrollment token (generated by an admin via
# POST /v1/devices/enrollment-tokens, or the operator console's Devices
# page), this is the only command needed to install, enroll, and start the
# agent. Safe to re-run -- an already-enrolled device is left untouched.
#
# Usage:
#   sudo ./install-linux-agent.sh --server-url https://api.example.com \
#     --enrollment-token <token> [--allowed-services svc1,svc2] [--external-id my-host] \
#     [--package-source <pip-installable target>]
#
# Requires: root (creates a system user and a system-level systemd unit),
# network access to the control plane, python3 with venv support.
#
# Packaging note: this repository has no published PyPI/private-index
# release yet, so --package-source defaults to installing straight from
# this repo's default branch via pip's git+https support -- fine for a
# demo/pilot, but for a real fleet rollout, publish a pinned wheel/sdist to
# a private index (or a signed release archive) and pass that URL/path via
# --package-source instead, so every endpoint installs an exact, reviewed
# version rather than "whatever main currently is."
set -euo pipefail

SERVICE_USER="helpdesk-agent"
INSTALL_DIR="/opt/helpdesktool"
CONFIG_DIR="/etc/helpdesktool"
CONFIG_FILE="$CONFIG_DIR/agent.json"
UNIT_NAME="helpdesk-linux-agent.service"
UNIT_PATH="/etc/systemd/system/$UNIT_NAME"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SERVER_URL=""
ENROLLMENT_TOKEN=""
EXTERNAL_ID=""
ALLOWED_SERVICES=""
PACKAGE_SOURCE="git+https://github.com/abdulnajam-boop/helpdesktool.git@main"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-url) SERVER_URL="$2"; shift 2 ;;
    --enrollment-token) ENROLLMENT_TOKEN="$2"; shift 2 ;;
    --external-id) EXTERNAL_ID="$2"; shift 2 ;;
    --allowed-services) ALLOWED_SERVICES="$2"; shift 2 ;;
    --package-source) PACKAGE_SOURCE="$2"; shift 2 ;;
    -h|--help)
      echo "usage: $0 --server-url <url> --enrollment-token <token> [--allowed-services svc1,svc2] [--external-id name] [--package-source target]"
      exit 0
      ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$SERVER_URL" || -z "$ENROLLMENT_TOKEN" ]]; then
  echo "usage: $0 --server-url <url> --enrollment-token <token> [--allowed-services svc1,svc2] [--external-id name]" >&2
  exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
  echo "this installer must be run as root (it creates a system user and a system service)" >&2
  exit 1
fi

PYTHON="${PYTHON:-python3}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  echo "$PYTHON was not found on PATH -- install Python 3.11 or newer first" >&2
  exit 1
fi
if ! "$PYTHON" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)'; then
  echo "$PYTHON is $($PYTHON --version 2>&1), but helpdesktool requires 3.11+." >&2
  echo "On Ubuntu 22.04 or older, install it first, e.g.:" >&2
  echo "  add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get install python3.11 python3.11-venv" >&2
  echo "then re-run this installer with: PYTHON=python3.11 $0 ..." >&2
  exit 1
fi

if [[ -z "$EXTERNAL_ID" ]]; then
  EXTERNAL_ID="$(hostname)"
fi

echo "==> Creating service account $SERVICE_USER (no login shell, no home directory)"
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

echo "==> Installing helpdesktool into $INSTALL_DIR (isolated virtualenv)"
mkdir -p "$INSTALL_DIR"
"$PYTHON" -m venv "$INSTALL_DIR/venv"
"$INSTALL_DIR/venv/bin/pip" install --upgrade pip --quiet
"$INSTALL_DIR/venv/bin/pip" install --upgrade "$PACKAGE_SOURCE" --quiet
chown -R "root:root" "$INSTALL_DIR"

mkdir -p "$CONFIG_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
  echo "==> $CONFIG_FILE already exists; leaving enrollment untouched (re-running is safe)"
else
  # Enroll (and run the first heartbeat/inventory cycle) as the unprivileged
  # service account from the very start, never as root -- runuser works
  # even though that account has no login shell (--shell /usr/sbin/nologin).
  echo "==> Enrolling device with the control plane as $SERVICE_USER"
  runuser -u "$SERVICE_USER" -- "$INSTALL_DIR/venv/bin/helpdesk-linux-agent" \
    --config "$CONFIG_FILE" \
    --server-url "$SERVER_URL" \
    --enrollment-token "$ENROLLMENT_TOKEN" \
    --external-id "$EXTERNAL_ID" \
    ${ALLOWED_SERVICES:+--allowed-services "$ALLOWED_SERVICES"} \
    --once
fi

find "$CONFIG_DIR" -type f -exec chmod 600 {} \;

echo "==> Installing systemd unit"
install -m 644 "$SCRIPT_DIR/$UNIT_NAME" "$UNIT_PATH"
systemctl daemon-reload
systemctl enable --now "$UNIT_NAME"

echo "==> Done. Check status with: systemctl status $UNIT_NAME"
echo "==> Logs: journalctl -u $UNIT_NAME -f"
