import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {api} from './api'
import './styles.css'

type Row=Record<string,any>
const nav=[['/','Dashboard'],['/devices','Devices'],['/tickets','Tickets'],['/incidents','Incidents'],['/actions','Actions'],['/approvals','Approvals'],['/audit','Audit'],['/integrations','Integrations'],['/settings','Settings']]
const nice=(value:any)=>value==null?'—':typeof value==='object'?JSON.stringify(value):String(value).replaceAll('_',' ')
const date=(value:any)=>value?new Date(value).toLocaleString():'Never'
function Badge({value}:{value:any}){return <span className={`badge ${String(value).toLowerCase()}`}>{nice(value)}</span>}
function Login({done}:{done:()=>void}){const [users,setUsers]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{api<Row[]>('/v1/auth/development/users').then(setUsers).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 async function login(id:string){try{const result=await api<Row>(`/v1/auth/development/login?user_id=${encodeURIComponent(id)}`,{method:'POST'});localStorage.setItem('helpdesk_session',result.access_token);done()}catch(e){setError((e as Error).message)}}
 return <main className="login"><section><div className="brandmark">H</div><h1>Helpdesktool</h1><p>Autonomous IT operations, with deterministic safety controls.</p><div className="dev-note">Development login · local environments only</div>{error&&<div className="error">{error}</div>}{loading?<p>Loading demo users…</p>:<div className="users">{users.map(u=><button key={u.id} onClick={()=>login(u.id)}><strong>{nice(u.role)}</strong><span>{u.email}</span></button>)}</div>}</section></main>}
function Table({rows,columns,onRow}:{rows:Row[],columns:[string,string][],onRow?:(row:Row)=>void}){if(!rows.length)return <div className="empty">No records yet.</div>;return <div className="tablewrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i} onClick={()=>onRow?.(row)} className={onRow?'clickable':''}>{columns.map(([k])=><td key={k}>{['status','severity','risk','os'].includes(k)?<Badge value={row[k]}/>:k.includes('_at')?date(row[k]):nice(row[k])}</td>)}</tr>)}</tbody></table></div>}
function Dashboard(){const [data,setData]=useLoad<Row>('/v1/dashboard');if(!data)return <Loading/>;return <><Title title="Operations overview" subtitle="Live tenant health and remediation activity"/><div className="cards">{Object.entries(data.counts).map(([k,v])=><article className="card" key={k}><span>{nice(k)}</span><strong>{String(v)}</strong></article>)}</div><div className="grid3"><Panel title="Recent incidents"><Table rows={data.recent_incidents} columns={[["summary","Incident"],["severity","Severity"],["status","Status"]]}/></Panel><Panel title="Recent tickets"><Table rows={data.recent_tickets} columns={[["title","Ticket"],["priority","Priority"],["status","Status"]]}/></Panel><Panel title="Recent actions"><Table rows={data.recent_actions} columns={[["skill_id","Action"],["risk","Risk"],["status","Status"]]}/></Panel></div></>}
function Resource({name,path,columns,detail=true}:{name:string,path:string,columns:[string,string][],detail?:boolean}){const [rows,reload,error]=useLoad<Row[]>(path);const [search,setSearch]=useState('');async function create(){try{if(name==='Tickets'){const title=prompt('Ticket summary');if(title)await api('/v1/tickets',{method:'POST',body:JSON.stringify({title,priority:'normal'})})}else if(name==='Actions'){const device_id=prompt('Device ID');const service=prompt('Allowlisted service name');if(device_id&&service)await api('/v1/actions',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({device_id,skill_id:'service.restart',parameters:{service}})})}reload()}catch(e){alert((e as Error).message)}}if(error)return <ErrorBox text={error}/>;if(!rows)return <Loading/>;const shown=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));return <><Title title={name} subtitle={`${rows.length} tenant-scoped records`}/><div className="resource-tools"><input className="search" placeholder={`Search ${name.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/>{['Tickets','Actions'].includes(name)&&<button onClick={create}>Create {name.slice(0,-1)}</button>}</div><Table rows={shown} columns={columns} onRow={detail?(r=>location.href=`/${name.toLowerCase()}/${r.id}`):undefined}/></>}
function Detail({kind,id}:{kind:string,id:string}){const singular=kind.endsWith('s')?kind.slice(0,-1):kind;const [row,,error]=useLoad<Row>(`/v1/${kind}/${id}`);if(error)return <ErrorBox text={error}/>;if(!row)return <Loading/>;return <><a className="back" href={`/${kind}`}>← Back to {kind}</a><Title title={row.hostname||row.title||row.summary||row.skill_id||singular} subtitle={`${singular} ${row.id}`}/><div className="detail">{Object.entries(row).map(([k,v])=><div key={k} className={typeof v==='object'?'wide':''}><label>{nice(k)}</label>{['status','severity','risk','os'].includes(k)?<Badge value={v}/>:<pre>{typeof v==='object'?JSON.stringify(v,null,2):k.includes('_at')?date(v):nice(v)}</pre>}</div>)}</div></>}
function Approvals(){const [rows,reload,error]=useLoad<Row[]>('/v1/approvals');async function decide(row:Row,decision:string){if(!confirm(`${decision} ${row.skill_id} on ${row.device_id}?`))return;await api(`/v1/actions/${row.id}/decision`,{method:'POST',body:JSON.stringify({decision,reason:'Decision from operator console'})});reload()}if(error)return <ErrorBox text={error}/>;return <><Title title="Approvals" subtitle="Human gate for medium and high-risk remediation"/>{!rows?<Loading/>:rows.length?<div className="approval-list">{rows.map(r=><article key={r.id}><div><h3>{r.skill_id}</h3><p>Device {r.device_id} · <Badge value={r.risk}/></p><pre>{JSON.stringify(r.parameters,null,2)}</pre></div><div><button onClick={()=>decide(r,'approve')}>Approve</button><button className="danger" onClick={()=>decide(r,'deny')}>Deny</button></div></article>)}</div>:<div className="empty">No actions are waiting for approval.</div>}</>}
function Integrations(){const [rows,reload,error]=useLoad<Row[]>('/v1/integrations/webhooks');const [form,setForm]=useState({name:'',url:'',secret_ref:'env:HELPDESK_WEBHOOK_SECRET_DEMO'});async function submit(e:React.FormEvent){e.preventDefault();await api('/v1/integrations/webhooks',{method:'POST',body:JSON.stringify({...form,event_types:['incident.created','remediation.succeeded']})});setForm({...form,name:'',url:''});reload()}return <><Title title="Integrations" subtitle="Signed webhooks for n8n and external automation"/>{error&&<ErrorBox text={error}/>}<form className="inline-form" onSubmit={submit}><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="url" placeholder="https://example.com/webhook" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><button>Create webhook</button></form>{rows&&<Table rows={rows} columns={[["name","Name"],["url","Endpoint"],["active","Active"],["event_types","Events"]]}/>}</>}
function Settings(){const [data,,error]=useLoad<Row>('/v1/settings');if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;return <><Title title="Settings" subtitle="Tenant policy and development environment"/><div className="settings"><Panel title="Tenant"><pre>{JSON.stringify(data.tenant,null,2)}</pre></Panel><Panel title="Incident policy"><p>Low disk threshold: <strong>{data.low_disk_threshold_percent}%</strong></p><p>Allowed services: {nice(data.allowed_services)}</p></Panel><Panel title="Environment"><p><Badge value={data.environment}/></p><p>Development login: {nice(data.development_login_enabled)}</p></Panel></div><Panel title="Users"><Table rows={data.users} columns={[["email","Email"],["role","Role"],["active","Active"]]}/></Panel></>}
function useLoad<T>(path:string):[T|undefined,()=>void,string]{const [data,setData]=useState<T>(),[error,setError]=useState(''),[n,setN]=useState(0);useEffect(()=>{api<T>(path).then(setData).catch(e=>setError(e.message))},[path,n]);return [data,()=>setN(v=>v+1),error]}
function Title({title,subtitle}:{title:string,subtitle:string}){return <header className="title"><div><h1>{title}</h1><p>{subtitle}</p></div></header>} function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>} function Loading(){return <div className="loading">Loading…</div>} function ErrorBox({text}:{text:string}){return <div className="error">{text}</div>}
function App(){const [session,setSession]=useState(!!localStorage.getItem('helpdesk_session'));if(!session)return <Login done={()=>setSession(true)}/>;const path=location.pathname,parts=path.split('/').filter(Boolean),page=parts[0]||'dashboard';let content:React.ReactNode=<Dashboard/>;if(parts[1])content=<Detail kind={parts[0]} id={parts[1]}/>;else if(page==='devices')content=<Resource name="Devices" path="/v1/devices" columns={[["hostname","Hostname"],["os","OS"],["last_seen_at","Last seen"]]}/>;else if(page==='tickets')content=<Resource name="Tickets" path="/v1/tickets" columns={[["title","Summary"],["priority","Priority"],["status","Status"],["updated_at","Updated"]]}/>;else if(page==='incidents')content=<Resource name="Incidents" path="/v1/incidents" columns={[["summary","Summary"],["severity","Severity"],["status","Status"],["occurrence_count","Occurrences"],["last_observed_at","Last observed"]]}/>;else if(page==='actions')content=<Resource name="Actions" path="/v1/actions" columns={[["skill_id","Skill"],["device_id","Device"],["risk","Risk"],["status","Status"],["created_at","Created"]]}/>;else if(page==='approvals')content=<Approvals/>;else if(page==='audit')content=<Resource name="Audit" path="/v1/audit" detail={false} columns={[["occurred_at","Timestamp"],["event_type","Event"],["actor_id","Actor"],["correlation_id","Resource"]]}/>;else if(page==='integrations')content=<Integrations/>;else if(page==='settings')content=<Settings/>;return <div className="shell"><aside><div className="logo"><span>H</span><b>Helpdesktool</b></div><nav>{nav.map(([href,label])=><a key={href} className={(href==='/'?path==='/':path.startsWith(href))?'active':''} href={href}>{label}</a>)}</nav><button className="logout" onClick={()=>{localStorage.removeItem('helpdesk_session');setSession(false)}}>Sign out</button></aside><main className="content"><div className="topbar"><span>Acme IT</span><Badge value="development"/></div>{content}</main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
